# agente/Dockerfile
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
  PIP_NO_CACHE_DIR=1

WORKDIR /app


RUN pip install --no-cache-dir poetry==1.8.3
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi --only main

# Copiar el código
COPY . /app

# uploads
RUN mkdir -p /app/uploads

EXPOSE 8000

# Entrypoint: API FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
